// Generates src/generated/credits.ts from openapi.json.
// Credit cost = x402 price / $0.01 (Nansen prices pay-per-request at $0.01 per credit, which matches
// the table at https://docs.nansen.ai/getting-started/credits). Endpoints without payment info are
// filled from that table via OVERRIDES. Run with: pnpm generate
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(fs.readFileSync(path.join(root, "openapi.json"), "utf8"));

const USD_PER_CREDIT = 0.01;
const OVERRIDES = {
  "/api/v1/account": 0,
  "/api/v1/search/general": 0,
  "/api/v1/search/entity-name": 0,
  "/api/v1/search/token-sectors": 1,
  "/api/v1/profiler/address/labels": 100,
  "/api/v1/profiler/address/premium-labels": 500,
  "/api/v1/portfolio/defi-holdings": 1,
};
// premium_labels=true is billed at 150 credits on these (changelog 17-07-2026).
const PREMIUM_LABEL_ENDPOINTS = [
  "/api/v1/tgm/holders",
  "/api/v1/tgm/pnl-leaderboard",
  "/api/v1/tgm/perp-pnl-leaderboard",
  "/api/v1/perp-leaderboard",
];
// Additional per-minute limits on top of plan limits (docs: rate-limits).
const ENDPOINT_RPM = {
  "/api/v1/search/token-sectors": 60,
  "/api/v1/tgm/perp-trades": 60,
  "/api/v1/profiler/perp-trades": 5,
  "/api/v1/search/web-search": 15,
  "/api/v1/search/web-fetch": 15,
};

const costs = {};
for (const [p, ops] of Object.entries(spec.paths)) {
  for (const [method, op] of Object.entries(ops)) {
    if (method !== "get" && method !== "post") continue;
    if (p in OVERRIDES) {
      costs[p] = OVERRIDES[p];
      continue;
    }
    const price = op["x-payment-info"]?.price;
    if (typeof price === "string") {
      costs[p] = Math.round(parseFloat(price.replace("$", "")) / USD_PER_CREDIT);
    }
  }
}

const sorted = Object.fromEntries(Object.entries(costs).sort(([a], [b]) => a.localeCompare(b)));
const ts = `// AUTO-GENERATED by scripts/gen-credits.mjs from openapi.json. Do not edit by hand.
// Credits per call by endpoint path. Endpoints absent here (trading, alerts) are not credit-metered.

export const CREDIT_COSTS: Readonly<Record<string, number>> = ${JSON.stringify(sorted, null, 2)} as const;

/** Endpoints that bill ${150} credits when \`premium_labels: true\` is sent. */
export const PREMIUM_LABEL_ENDPOINTS: readonly string[] = ${JSON.stringify(PREMIUM_LABEL_ENDPOINTS, null, 2)} as const;

export const PREMIUM_LABEL_COST = 150;

/** Endpoint-specific per-minute request limits that apply on top of plan limits. */
export const ENDPOINT_RPM: Readonly<Record<string, number>> = ${JSON.stringify(ENDPOINT_RPM, null, 2)} as const;

export const SPEC_VERSION = ${JSON.stringify(spec.info?.version ?? "unknown")};
export const SPEC_PATH_COUNT = ${Object.keys(spec.paths).length};
`;
fs.mkdirSync(path.join(root, "src/generated"), { recursive: true });
fs.writeFileSync(path.join(root, "src/generated/credits.ts"), ts);
console.log(`credits.ts: ${Object.keys(sorted).length} metered endpoints`);
